apiVersion: v1
kind: ConfigMap
metadata:
  name: avalanche-config-for-scaler
  namespace: prombench-{{ .PR_NUMBER }}
data:
  webserver.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: avalanche
      namespace: prombench-{{ .PR_NUMBER }}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: avalanche
      template:
        metadata:
          namespace: prombench-{{ .PR_NUMBER }}
          labels:
            app: avalanche
        spec:
          containers:
          - name: avalanche
            image: quay.io/freshtracks.io/avalanche:latest
            # The args can be changed based on https://github.com/prometheus-community/avalanche/blob/main/cmd/avalanche.go#L32-L52
            args:
            - "--metric-count=5"
            - "--series-count=5"
            - "--value-interval=30"
            - "--metric-interval=30"
            - "--port=9001"
            ports:
            - name: metrics1
              containerPort: 9001
          nodeSelector:
            node-name: nodes-{{ .PR_NUMBER }}
            isolation: none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
  namespace: prombench-{{ .PR_NUMBER }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalanche
  template:
    metadata:
      namespace: prombench-{{ .PR_NUMBER }}
      labels:
        app: avalanche
    spec:
      containers:
      - name: avalanche
        image: quay.io/freshtracks.io/avalanche:latest
        # The args can be changed based on https://github.com/prometheus-community/avalanche/blob/main/cmd/avalanche.go#L32-L52
        args:
        - "--metric-count=5"
        - "--series-count=5"
        - "--value-interval=30"
        - "--metric-interval=30"
        - "--port=9001"
        ports:
        - name: metrics1
          containerPort: 9001
      nodeSelector:
        node-name: nodes-{{ .PR_NUMBER }}
        isolation: none
---
apiVersion: v1
kind: Service
metadata:
  name: avalanche
  namespace: prombench-{{ .PR_NUMBER }}
  labels:
    app: avalanche
    monitored: "true"
spec:
  ports:
  - name: metrics1
    port: 8080
    targetPort: metrics1
  - name: metrics2
    port: 8081
    targetPort: metrics2
  - name: metrics3
    port: 8082
    targetPort: metrics3
  - name: metrics4
    port: 8083
    targetPort: metrics4
  - name: metrics5
    port: 8084
    targetPort: metrics5
  selector:
    app: avalanche
