name: "Publishing the container image"
on:
  push:
    branches:
    - master
  workflow_dispatch: {}
  
env:
  GITHUB_ORG: ${{ github.repository_owner }} # GoogleCloudPlatform
  GITHUB_REPO: ${{ github.event.repository.name }} # prometheus-test-infra
  IMAGE_REGISTRY: ghcr.io

jobs:
  build-and-push-docker-image:
    name: Build the image and push to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go build
        run: |
          cd infra
          go build .
          cd ..

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish the container image
        run: |
          
          IMAGE_ID="${IMAGE_REGISTRY}/${GITHUB_ORG}/${GITHUB_REPO}/prombench"
          
          # Converting all uppercase letters to lowercase (as GHCR does not allow uppercase in the name of the image)
          IMAGE_ID=$(echo "${IMAGE_ID}" | tr '[:upper:]' '[:lower:]')
          
          IMAGE_TAG="latest"
          
          docker build prombench/ --tag "${IMAGE_ID}:${IMAGE_TAG}"
          docker push "${IMAGE_ID}:${IMAGE_TAG}"
